# Generated by Django 3.2.6 on 2021-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='delta',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='problem',
            name='epsilon',
            field=models.FloatField(default=0.01),
        ),
    ]
